# Generated by Django 3.2.3 on 2021-06-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diner_app', '0002_remove_favorites_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='uuid',
            new_name='uuid_fp',
        ),
        migrations.AddField(
            model_name='favorites',
            name='uuid_ue',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
