# Generated by Django 3.2.3 on 2021-06-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diner_app', '0003_auto_20210612_1108'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorites',
            index=models.Index(fields=['created_at'], name='Diner_app_f_created_3eab83_idx'),
        ),
        migrations.AddIndex(
            model_name='favorites',
            index=models.Index(fields=['user'], name='Diner_app_f_user_id_b5afbc_idx'),
        ),
    ]
