# Generated by Django 3.2.3 on 2021-06-13 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Diner_app', '0004_auto_20210612_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noteq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_ue', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('uuid_fp', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('uuid_gm', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
