# Generated by Django 3.2.3 on 2021-06-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diner_app', '0005_noteq'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='favorites',
            index=models.Index(fields=['user', 'uuid_ue', 'uuid_fp'], name='Diner_app_f_user_id_11c82f_idx'),
        ),
        migrations.AddIndex(
            model_name='favorites',
            index=models.Index(fields=['user', 'activate'], name='Diner_app_f_user_id_6ea47c_idx'),
        ),
        migrations.AddIndex(
            model_name='favorites',
            index=models.Index(fields=['-updated_at'], name='Diner_app_f_updated_dd45e5_idx'),
        ),
    ]
